import {
  Activity,
  Archive,
  BarChart3,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  ClipboardPen,
  Cog,
  Dumbbell,
  DumbbellIcon,
  Globe,
  GraduationCap,
  Hammer,
  History,
  Home,
  LayoutDashboard,
  LibraryBig,
  LineChart,
  Monitor,
  Newspaper,
  PlayCircle,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShieldUser,
  Signal,
  SunSnow,
  Swords,
  Trophy,
  UserRound,
  Users,
  Users2,
} from "lucide-react";
import React from "react";

export const ICON_MAP = {
  Globe,
  LayoutDashboard,
  Hammer,
  Building2,
  GraduationCap,
  Users2,
  UserRound,
  ShieldCheck,
  Shield,
  PlayCircle,
  Dumbbell,
  ClipboardCheck,
  BarChart3,
  Swords,
  Calendar,
  Cog,
  Trophy,
  CalendarCheck,
  LineChart,
  History,
  Newspaper,
  Home,
  CalendarDays,
  SunSnow,
  Users,
  CalendarCheck2,
  ClipboardList,
  Activity,
  CalendarClock,
  ClipboardPen,
  Signal,
  Archive,
  LibraryBig,
  DumbbellIcon,
  Monitor,
  Settings,
  Settings2,
  ShieldUser,
};

export const getIcon = (iconName: string): React.ReactNode => {
  const Icon = ICON_MAP[iconName as keyof typeof ICON_MAP];
  return Icon ? <Icon className="h-4 w-4" /> : null;
};
