# .github/workflows/test.yml
name: Test Workflow

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello World! This workflow is working."
